/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador_assembly;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.BufferedOutputStream;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;


/**
 *
 * @author gundo
 */
public class Compilador extends javax.swing.JFrame {
    /**
     * Creates new form Compilador
     */
   
    int alterna  = 0;
    private JTextPane zNum, tField;
    private Font font = new Font("Source Code Pro", Font.PLAIN, 12);
    public String vez = "nada";
    public String diretorio_vez = "";
    
    public void setVez(String arq){
        this.vez = arq;
    }
    
    public void setDiretorio(String dir){
        this.diretorio_vez = dir;
    }

    
    public Compilador() {
        initComponents(); 
         
        String currentDir = System.getProperty("user.dir");
        this.logo.setIcon(new ImageIcon(currentDir + File.separator + "imagens" + File.separator + "logo.png"));
        this.Botao_compila.setIcon(new ImageIcon(currentDir + File.separator + "imagens" + File.separator + "compila.png"));
        
        zNum = new JTextPane();
        zNum.setText(contaLinhas(Painel_de_escrita.getText()));
        zNum.setEditable(false);
        zNum.setBorder(new EmptyBorder(2, 6, 2, 6));
        zNum.setBackground(Color.LIGHT_GRAY);
        zNum.setFont(font);
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(zNum, BorderLayout.LINE_START);
        jPanel1.add(Painel_de_escrita, BorderLayout.CENTER);
        jPanel1.setBackground(Color.LIGHT_GRAY);
        

        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        getContentPane().add(jScrollPane1, BorderLayout.CENTER);
        
        
        
        StyleContext styleContext = new StyleContext();
        Style defaultStyle = styleContext.getStyle(StyleContext.DEFAULT_STYLE);
        Style cwStyle = styleContext.addStyle("ConstantWidth", null);
        StyleConstants.setForeground(cwStyle, Color.BLUE);
        StyleConstants.setBold(cwStyle, true);
        KeywordStyledDocument ksd = new KeywordStyledDocument(defaultStyle, cwStyle);
        Painel_de_escrita.setStyledDocument(ksd);
    }

    /**
     * This method is called from within the' constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botao_compila = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Painel_de_resposta = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        informa = new javax.swing.JLabel();
        linhas = new javax.swing.JLabel();
        Caracteres = new javax.swing.JLabel();
        rolagem_principal = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Painel_de_escrita = new javax.swing.JTextPane();
        logo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Salvar_codigo = new javax.swing.JMenu();
        Botao_salva = new javax.swing.JMenuItem();
        carrega = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assembletion");
        setBackground(new java.awt.Color(245, 245, 245));
        setResizable(false);

        Botao_compila.setToolTipText("Compilar");
        Botao_compila.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Botao_compila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_compilaActionPerformed(evt);
            }
        });

        Painel_de_resposta.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        Painel_de_resposta.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jScrollPane2.setViewportView(Painel_de_resposta);

        informa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        informa.setText("Informações:");

        int linha = this.Painel_de_escrita.getText().split("\n").length;
        this.linhas.setText("Linhas: " + Integer.toString(linha));

        String total[] = this.Painel_de_escrita.getText().split("\n");
        int caracteres = 0;
        for (String total1 : total) {
            caracteres += total1.length();
        }
        this.Caracteres.setText("Caracteres:" + Integer.toString(caracteres));

        jScrollPane1.setViewportView(Painel_de_escrita);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        rolagem_principal.setViewportView(jPanel1);

        Salvar_codigo.setText("Sistema");
        Salvar_codigo.setToolTipText("Salvar (Ctrl + D)");
        Salvar_codigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Botao_salva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        Botao_salva.setText("Salvar");
        Botao_salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_salvaActionPerformed(evt);
            }
        });
        Salvar_codigo.add(Botao_salva);

        carrega.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        carrega.setText("Carregar");
        carrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregaActionPerformed(evt);
            }
        });
        Salvar_codigo.add(carrega);

        jMenuBar1.add(Salvar_codigo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rolagem_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(linhas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(informa))
                                .addGap(18, 18, 18)
                                .addComponent(Botao_compila, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Caracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(informa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(linhas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Botao_compila, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(4, 4, 4)
                                .addComponent(Caracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rolagem_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(543, 543, 543))))
        );

        informa.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleDescription("Compilador assembly");

        setSize(new java.awt.Dimension(932, 719));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    @SuppressWarnings("empty-statement")
    private void Botao_compilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_compilaActionPerformed
        
        if(vez.equals("nada")){
           JOptionPane.showMessageDialog(this,"Salvar arquivo ou carregar arquivo");
        }
        else{    
           
            try {
                File arq = new File("teste.txt");
                arq.createNewFile();
                BufferedWriter writer = new BufferedWriter(new FileWriter(arq));
                writer.write(this.Painel_de_escrita.getText());
                writer.flush();
                writer.close();

                compilar comp = new compilar("", diretorio_vez,this.getNome(vez), "teste.txt");
                String Resultado = comp.execultar();
                
                arq.delete();
                
                threadCarrega carrega = new threadCarrega(Painel_de_resposta,Resultado);
                carrega.start();
                
            } catch (IOException ex) {
                Logger.getLogger(Compilador.class.getName()).log(Level.SEVERE, null, ex);
            }
     
        }
        
    }//GEN-LAST:event_Botao_compilaActionPerformed
    
    private void Botao_salvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_salvaActionPerformed
        String currentDir = System.getProperty("user.dir");
        File atual = new File(currentDir + File.separator + "códigos");
        JFileChooser chooser = new JFileChooser(atual);
        
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int retorno = chooser.showSaveDialog(this);
        
        if(retorno == JFileChooser.APPROVE_OPTION){
            File select = chooser.getSelectedFile();
            
            String fileName = JOptionPane.showInputDialog("File name", "none.dat");
            if (!fileName.endsWith(".dat")) {
                fileName += ".dat";
            }
            
            Codigo_assembly cod = new Codigo_assembly();
            cod.setCodigo(Painel_de_escrita.getText());
            
            try {
                ObjectOutputStream objectOut = new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream(select.getAbsolutePath() + File.separator + fileName)));
                objectOut.writeObject(cod);
                objectOut.close();
                this.setVez(fileName);
                this.setDiretorio(select.getAbsolutePath());
            } catch (IOException ex) {System.out.print("erro");}
           
            
        }      
    }//GEN-LAST:event_Botao_salvaActionPerformed

    
    
    private void carregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregaActionPerformed
        Loader load = new Loader();
        load.setComp(this);
        load.seta(this.Painel_de_escrita);
        load.setVisible(true);
    }//GEN-LAST:event_carregaActionPerformed
    
    public String getNome(String arq){
        String nome = "";
        for (int i=0; i< arq.length(); i++) {
            char c = arq.charAt(i);
            nome += c;
            if(c == '.'){ break;}
        }
        return nome;
    }
    
    public String contaLinhas(String t){
    String l = "0";
    int lin = 0;
    for (int i=0; i<t.length(); i++) {
        char c = t.charAt(i);
        if(c == '\n'){
            lin ++;
            l += "\n" + Integer.toString(lin);
        }
    }
    return l;
    }
    
    public void seta(){
        int linha = this.Painel_de_escrita.getText().split("\n").length;
        String total[] = this.Painel_de_escrita.getText().split("\n");
        int caracteres = 0;
        for (String total1 : total) {
            caracteres += total1.length();
        }
        this.linhas.setText("Linhas: " + Integer.toString(linha));
        this.Caracteres.setText("Caracteres:" + Integer.toString(caracteres));
        zNum.setText(contaLinhas(Painel_de_escrita.getText()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compilador().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Botao_compila;
    private javax.swing.JMenuItem Botao_salva;
    private javax.swing.JLabel Caracteres;
    private javax.swing.JTextPane Painel_de_escrita;
    private javax.swing.JTextPane Painel_de_resposta;
    private javax.swing.JMenu Salvar_codigo;
    private javax.swing.JMenuItem carrega;
    private javax.swing.JLabel informa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel linhas;
    private javax.swing.JLabel logo;
    private javax.swing.JScrollPane rolagem_principal;
    // End of variables declaration//GEN-END:variables
}
